In [1]:
import tensorflow as tf
print("tensorflow version: {}".format(tf.__version__))

tensorflow version: 2.18.0


In [2]:
d0=tf.constant(1)
print("Dimention is",tf.rank(d0).numpy())
print(d0)

Dimention is 0
tf.Tensor(1, shape=(), dtype=int32)


In [3]:
n=1 # vector

In [4]:
d1=tf.constant((2,))
print("Dimention is",tf.rank(d1).numpy())
print(d1)

Dimention is 1
tf.Tensor([2], shape=(1,), dtype=int32)


In [5]:
n=2 # martix

In [6]:
d2=tf.constant((2,2))
print("Dimention is",tf.rank(d2).numpy())
print(d2)

Dimention is 1
tf.Tensor([2 2], shape=(2,), dtype=int32)


In [7]:
n=3 #martix

In [8]:
d3=tf.constant((2,2,2))
print("Dimention is",tf.rank(d3).numpy())
print(d3)

Dimention is 1
tf.Tensor([2 2 2], shape=(3,), dtype=int32)


In [9]:
#rank 0 tensor
x1=tf.Variable(23)
#rank 3 tensor
x2= tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]])
#python variable
x0=123
print(x1)
print(x2)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>
<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


In [10]:
# assign constant

In [11]:
x1.assign(100)
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

In [13]:
x1= tf.Variable(100)
print(x1)
x1.assign(200)
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=200>

In [14]:
x2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [15]:
x0

123

In [16]:
#reshape

In [17]:
x112 = tf.reshape(x2,[1,12]) # 12 row 1 coulmn
x112

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

In [18]:
xf64 = tf.Variable(202,dtype=tf.float64)
xf64

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=202.0>

In [19]:
tf.float64

tf.float64

In [20]:
xf64.numpy()

np.float64(202.0)

In [21]:
tf.rank(xf64)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [22]:
tf.rank(x2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [23]:
t=tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tf.rank(t).numpy()

np.int32(3)

In [24]:
t.numpy()

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

In [25]:
tensor3 =t[1,1,2] #slice 1, row 0,column2
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [26]:
x= tf.constant([0,1,1,2,3,4,8,13,21,34])
print("Before 4:",x[:4].numpy())
print("After 4:",x[4:].numpy())
print("From 2, before 7:",x[2:7].numpy())
print("Every other item:",x[::2].numpy())
print("Reversed:",x[::-1].numpy())

Before 4: [0 1 1 2]
After 4: [ 3  4  8 13 21 34]
From 2, before 7: [1 2 3 4 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  4  3  2  1  1  0]


In [27]:
a= tf.Variable([[1,2],[3,4]])
i=tf.cast(a,dtype=tf.float32)
print(a)
print(i)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [28]:
a=tf.Variable([[1,2],[3,4]])
b=tf.Variable([[5,6],[7,8]])
c=a+b

In [29]:
b.numpy()

array([[5, 6],
       [7, 8]], dtype=int32)

In [31]:
print(a)
print(b)
print("\n output of c",c)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>

 output of c tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [32]:
d =tf.square(c)
print(d)

tf.Tensor(
[[ 36  64]
 [100 144]], shape=(2, 2), dtype=int32)


In [34]:
tf.add(a,b)
tf.subtract(b,a)
e= a*b
print(6)
tf.multiply(a,b) # No of columns in a == No of Rows in b tensor

6


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>